<?php

/**
 * 	[name, thumb location, description, token, skip documentation]
 */
$componentsArray = array(
	array("Accordion", "accordion.jpg", "Custom viewstack component.", "accordion"),
	array("AnimatedImage", "animatedImage.jpg", "Bitmap animations with granular control over framerates.", "animatedImage"),
	array("AutoComplete", "autoComplete.jpg", "Real-time DropDownList filtering.", "autoComplete"),
	array("AutoFitText", "autoFitText.jpg", "Text components that automatically size to fit the available space.", "autoFitText"),
	array("BarCode", "barCode.jpg", "Generates and displays various bar codes.", "barCode"),
	array("BitmapAdjustments", "bitmapAdjustments.jpg", "Effects and changes for bitmap data.", "bitmapAdjustments"),
	array("ButtonBar", "buttonBar.jpg", "Button bar that supports dragging, closing, and animation.", "buttonBar"),
	array("Calculator", "calculator.jpg", "Stand-alone or grid editor calculator.", "calculator"),
	array("Calendar", "calendar.jpg", "Full featured Calendar.", "calendar"),
	array("CAPTCHA", "captcha.jpg", "Audio and/or visual test if the user is human.", "captcha"),
	array("CarouselLayout", "carouselLayout.jpg", "CarouselLayout generalized layout class.", "carouselLayout"),
	array("CarouselList", "carouselList.jpg", "List optimized for use by the CarouselLayout class.", "carouselList"),
	array("Clocks", "clocks.jpg", "Analog and digital clock.", "clocks"),
	array("Colorizer", "colorizer.jpg", "Component that returns colors based on passed values.", "colorizer"),
	array("ColorPicker", "colorPicker.jpg", "Spark color picker with enhanced customization.", "colorPicker"),
	array("ColorSpacePicker", "colorSpacePicker.jpg", "Color space picker.", "colorSpacePicker"),
	array("CompassContainer", "compassContainer.jpg", "Container with north, east, south, west, and center regions.", "compassContainer"),
	array("CoverflowLayout", "coverflowLayout.jpg", "Coverflow generalized layout class.", "coverflowLayout"),
	array("CoverflowList", "coverflowList.jpg", "List optimized for use by the CoverflowLayout class.", "coverflowList"),
	array("CursorManager", "cursorManager.jpg", "Add, display, and manage native mouse cursors.", "cursorManager"),
	array("DatePicker", "datePicker.jpg", "Spark based DatePicker that supports skinning and custom renderers.", "datePicker"),
	array("DockingCompassContainer", "dockingCompassContainer.jpg", "CompassContainer that allows dragging and docking of regions.", "dockingCompassContainer"),
	array("Donut Chart", "donut.jpg", "Supports several rings of data series.", "donut"),
	array("ExpandingContainer", "expandingContainer.jpg", "Expandable/collapsible skinnable container.", "expandingContainer"),
	array("FieldSet", "fieldSet.jpg", "Fieldset container similiar to a HTML fieldset.", "fieldSet"),
	array("Filters", "filters.jpg", "Additional bitmap filters.", "filters"),
	array("FlexContextMenu", "flexContextMenu.jpg", "Context menu that opens on right-click.", "flexContextMenu"),
	array("FloatPaneControlBar", "floatPaneControlBar.jpg", "Control bar used to manage floated Panes.", "floatPaneControlBar"),
	array("Funnel Chart", "funnel.jpg", "Chart that displays data in a funnel pattern.", "funnel"),
	array("GraphicsEditor", "graphicsEditor.jpg", "Graphics editor.", "graphicsEditor"),
	array("Heatmap", "heatmap.jpg", "Chart that displays data via colorizers.", "heatmap"),
	array("HtmlDragDrop", "htmlDragDrop.jpg", "Accept file drops from the user's desktop via the HTML 5 API.", "htmlDragDrop"),
	array("HtmlFrame", "htmlFrame.jpg", "Display html content inside a flex application.", "htmlFrame"),
	array("HtmlGeolocation", "htmlGeolocation.jpg", "Retrieve user location via HTML 5 API.", "htmlGeolocation"),
	array("iCalendarParser", "iCalendarParser.jpg", "Exports/imports iCalendar formatted strings.", "iCalendarParser"),
	array("iCalendarRecurrence", "iCalendarRecurrence.jpg", "Generates and returns recurring dates based on the iCalendar spec.", "iCalendarRecurrence"),
	array("IconButton", "iconButton.jpg", "A button designed to display icons with a flyout label.", "iconButton"),
	array("Linear Gauges", "linearGauges.jpg", "Horizontal and vertical gauge sliders with advanced features.", "linearGauges"),
	array("Magnifier", "magnifier.jpg", "Apply a magnification to visual components.", "magnifier"),
	array("Menu and MenuBar", "menuBar.jpg", "Extended Halo Menu and MenuBar that adds customization options.", "menuBar"),
	array("MiniViewport", "miniViewport.jpg", "Small viewport designed to help the user navigate scrollable content.", "miniViewport"),
	array("PackedLayout", "packedLayout.jpg", "Layout that minimizes element overlap.", "packedLayout"),
	array("PackedList", "packedList.jpg", "PackedLayout List with support for throwing.", "packedList"),
	array("Pane", "pane.jpg", "Containers that can be floated and behave like windows.", "pane"),
	array("TabPaneNavigator", "tabPaneNavigator.jpg", "Tabbed viewstack designed for docking Pane containers.", "tabPaneNavigator"),
	array("PopUpButton", "popUpButton.jpg", "Button that can also open popup content.", "popUpButton"),
	array("ProgressDisplay", "progressDisplay.jpg", "Progress indicators.", "progressDisplay"),
	array("Radar", "radar.jpg", "Also known as a polar, spider chart, or a kiviat diagram.", "radar"),
	array("Radial Gauge", "radialGauge.jpg", "Circular gauge used to select numerical values.", "radialGauge"),
	array("Rating", "rating.jpg", "Used to rate content.", "rating"),
	array("RichTextEditor", "richTextEditor.jpg", "Toolbar that manages Text Layout Framework based controls.", "richTextEditor"),
	array("RotaryField", "rotaryField.jpg", "Control used to select angles.", "rotaryField"),
	array("SafariMouseWheelFix", "safariMouseWheelFix.jpg", "Adds mouse wheel support to content running in Safari.", "safariMouseWheelFix"),
	array("Scroller", "scroller.jpg", "Scroller with granular control over the pixels scrolled.", "scroller"),
	array("Separators", "separator.jpg", "Simple analog to a HTML HR display element with padding support.", "separator"),
	array("SliderField", "sliderField.jpg", "Control used to select a numerical value.", "sliderField"),
	array("Sparklines", "sparklines.jpg", "Small bar and line charts useful in grids.", "sparklines"),
	array("TextInput", "textInput.jpg", "TextInput with icon and clearing support.", "textInput"),
	array("TimebarContainer", "timebarContainer.jpg", "Container used to select and display time periods.", "timebarContainer"),
	array("Timeline", "timeline.jpg", "Display events along a Timebar.", "timeline"),
	array("TimeMachineLayout", "timeMachineLayout.jpg", "TimeMachine generalized layout class.", "timeMachineLayout"),
	array("TimeMachineList", "timeMachineList.jpg", "List optimized for use by the TimeMachineLayout class.", "timeMachineList"),
	array("TimePicker", "timePicker.jpg", "Control used to select a time, specific to the minute.", "timePicker"),
	array("ToggleSwitchDesktop", "toggleSwitchDesktop.jpg", "ToggleSwitch component designed for desktop use.", "toggleSwitchDesktop"),
	array("Toolbar", "toolbar.jpg", "Container used to display toolbar content.", "toolbar", true),
	array("TransformContainer", "transformContainer.jpg", "Enables dragging and transformations for child content.", "transformContainer"),
	array("TreeMap", "treeMap.jpg", "Displays hierarchical data by using nested rectangles.", "treeMap"),
	array("ReflectionContainer", "reflectionContainer.jpg", "Simple and performant reflection container.", "reflectionContainer"),
	array("Utilities", "utilities.jpg", "Mountain of utility classes.", "utilities", true),
	array("ViewStack", "viewstack.jpg", "Container that displays one child element at a time.", "viewStack"),
	array("WheelList", "wheelList.jpg", "A list with renderers arranged as slices of an ellipse.", "wheelList")
);

?>